name: CI devops 2022 EPF
on:
  push:
    branches: 
      -master
      
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-18.04
    steps:
    
      - name: Set up checkout
        uses: actions/checkout@v2.3.3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with: 
          distribution: "temurin"
          java-version: "11"
          cache: "maven"
 
      - name: Build and test with Maven
        run: mvn package --file simple-api/pom.xml
